### PR TITLE
Update passphrase-existing.html

### PR DESCRIPTION
**Pull request by mdw**
fix to deter shoulder surfing by changing passphrase input field type from `text` to `password` 

passphrase-existing-html

### CODE REVIEW

**Comment by jdogresorg** [comment]
Users should not be entering their wallet passphrase while anyone is around, and this is something that should be done once and not repeatedly, so I do not see this as much of an issue.

IMO Hiding the passphrase with type="password" with no option to see what was typed and verify that everything has been typed correctly, with spaces, in the correct order, is not something that I consider very user friendly. I feel it is more important for people to be able to see exactly what they have typed for verification purposes.

I may consider switching the default passphrase entry box to type="password" in the future, as long as there is an option to see the "plaintext" passphrase being entered for verification purposes. (Perhaps a icon that when clicked switches from type="password" to type="text")

I envision something like this, with a clickable icon on the field to reveal the passphrase:
image

Thank you for this PR request... If you want to update the PR to include the above mentioned functionality, I will consider merging it... otherwise, I will add this functionality in a future release as it is a pretty easy tweak :) Good suggestion :)

**Comment by mdw** [comment]
That's smart, adding a toggle icon is absolutely the thing to do. I see you're using font-awesome, so I think using that icon will do the trick. Would require adding that little bit of JS to `freewallet-desktop.js`in order to toggle (unless there's a CSS way) if that sounds OK to you.

**Comment by jdogresorg** [comment]
Glad that you agree... it won't require tweaks to freewallet-desktop.js as that is all generalized functions for use throughout the wallet, not page-specific code.

If you want to take a stab at this update, you should be able to update passphrase-existing.html only, as that is where the HTML is, as well as the javascript that handles toggling the passphrase type, handling clicking ok/cancel, etc.

https://github.com/jdogresorg/freewallet-desktop/blob/master/html/passphrase-existing.html

**Comment by mdw** [comment]
needed a bit of CSS to position fa-eye icon, added to `css/freewallet-desktop.css` 
one div and one function to handle click event added to `html/existing-passphrase.html`

show
hide

**Comment by jdogresorg** [comment]
Looks good… will review/test next week when I am back from vacation in Seattle… thanks

**Pull request merged**
